---
name: Jens Daniel
surname: Müller
position: "Postdoctoral Researcher"
profilepic: portrait_JDM_square.jpg
address: "ETH Zurich | Department of Environmental Systems Science"
www: jens-daniel-mueller.github.io
email: "jensdaniel.mueller@usys.ethz.ch"
twitter: Jens_D_Mueller
github: jens-daniel-mueller
orcid: 0000-0003-3137-0883
aboutme: Ocean biogeochemist with a favour for carbon, observations and a pinch of data science
headcolor: 005f73
date: "`r format(Sys.time(), '%B %Y')`"
csl: "csl/copernicus-publications_jdm.csl"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
```

# Brief bio

# Key publications

```{r}

bibliography_entries("publication_list_jdm.bib") %>%
  filter(id %in% c("muller_long-term_2016",
                   "muller_metrology_2018",
                   "gruber_trends_2023",
                   "muller_decadal_2023",
                   "schneider_biogeochemical_2018"))


```



# Education

```{r}

tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~Why,
  
  "PhD Chemical Oceanography", 
  "07 / 2014 – 06 /2018", 
  "Leibniz-Institute for Baltic Sea Research Warnemünde (IOW)", 
  "Warnemünde, Germany",
  c("Ocean Acidification in the Baltic Sea: Involved Processes, Metrology of pH in Brackish Waters, and Calcification under Fluctuating Conditions",
    "Grade: With honors (Summa cum laude)"),
  
  "MSc Biological Oceanography", 
  "09 / 2010 – 08 / 2012", 
  "GEOMAR Helmholtz Centre for Ocean Research Kiel", 
  "Kiel, Germany",
  "Grade: 1.2 (ECTS grade, A Excellent)",

  "BSc Chemistry", 
  "09 / 2008 – 08 / 2009", 
  "Phillips-University Marburg", 
  "Marburg, Germany",
  "Grade: 1.7 (ECTS grade B “Very good”)"
) %>%
  detailed_entries(Institution, Year, Degree, Where, Why)
```


# Employment and occupation

```{r}

tribble(
  ~ Role,
  ~ Year,
  ~ Institution,
  ~ Where,
  ~ Details,
  
  "Postdoctoral researcher",
  "07 /2020 - present",
  "ETH Zürich",
  "Zurich, Switzerland",
  "Environmental Physics | Prof. Dr. Nicolas Gruber",
  
  "Postdoctoral researcher",
  "07 / 2018 – 06 /2020",
  "Leibniz-Institute for Baltic Sea Research Warnemünde (IOW)",
  "Warnemünde, Germany",
  "Trace gas biogeochemistry | Prof. Dr. Gregor Rehder",
  
  "Scientific Employee",
  "10 / 2013 – 03 / 2014",
  "GEOMAR Helmholtz Centre for Ocean Research Kiel",
  "Kiel, Germany",
  c(
    "Benthic Ecology | Prof. Dr. M. Wahl",
    "Marine Biogeochemistry | Prof. Dr. U. Riebesell"
  ),
  
  "Sailing Instructor",
  "07 – 10 / 2013 ",
  "Kiel Marketing GmbH | Camp 24/7",
  "Kiel, Germany",
  c(),
  
  "Divemaster",
  "01 – 03 / 2013",
  "Al Dive dive centre",
  "Loubiere, Dominica",
  c(),
  
  "Research Assistant",
  "05 – 08 / 2010",
  "GEOMAR Helmholtz Centre for Ocean Research Kiel",
  "Kiel, Germany",
  "Evolutionary Ecology of Marine Fishes | Prof. Dr. T. Reusch"
  
) %>%
  detailed_entries(Institution, Year, Role, Where, Details)


```

# Publications

## Peer reviewed

```{r}

bibliography_entries("publication_list_jdm.bib") %>%
  filter(type == "article-journal")


```

## In review

```{r}

bibliography_entries("publication_list_jdm.bib") %>%
  filter(type == "report")


```

## Books

```{r}

bibliography_entries("publication_list_jdm.bib") %>%
  filter(type == "book")


```

## Thesis

```{r}

bibliography_entries("publication_list_jdm.bib") %>%
  filter(type == "thesis")


```

## Datasets

```{r}

bibliography_entries("publication_list_jdm.bib") %>%
  filter(type == "")


```

## Selected conference presentations

# Teaching experience

```{r, eval=FALSE}
University of Rostock
SS 2019
Analytical and Environmental Chemistry I

Dissolved Gases
03.06.2019 | Slides

Water
03.06.2019 | Slides
WS 2018/19
Analytical Chemistry 4: Environmental Chemistry

Dissolved Gases
14.01.2019 | Slides

Current topic: Baltic Sea Biogeochemistry
16.01.2019 | Slides
```



# Funding

```{r}


tribble(
  ~ Year,
  ~ Award,
  ~ Institution,
  ~ comment,
  ~ detail,
  
  "2019-2022",
  "SPECTROPHABS",
  "BSH",
  "Spectrophotometric pH-measurements for monitoring of marine acidification in the Baltic Sea",
  "co-applicant",
  
  "2018",
  "Early-Career Grant",
  "National Geographic Society",
  "Financial and outreach support for Bloomsail expedition",
  c(),
  
  "2010 - 2018",
  "Academic Scholarships",
  "German Academic Scholarship Foundation",
  "Multiple fundings granted independently",
  c(
    "PhD scholarship (ideational)",
    "Full student scholarship",
    "Field work grant, Patagonia, Chile",
    "Advanced English course, Bath, England",
    "Summer academy, San Giovanni, Italy"
  )
) %>%
  detailed_entries(comment, Year, Award, Institution, detail)


```


# Honors and Awards

```{r}

tribble(
  ~ Year, ~ Award, ~ Institution, ~comment,
  
"2019",
"Briese Award",
"Shipping company Briese",
"Outstanding PhD thesis in Marine Research",

"2019",
"Dissertation award",
"German Water Chemical Society",
"Outstanding PhD thesis in Water Chemistry, sponsored by Walter-Kölle foundation",

"2019",
"Dissertation award",
"Baltic Sea Research Foundation",
"Outstanding PhD thesis in Baltic Sea Science",

"2017",
"Best poster award",
"Baltic Sea Science Congress", 
"for presentation by newcomers",

"2005",
"Book-price",
"Bertha-von-Suttner Gymnasium",
"for extraordinary achievements during the Abitur",

) %>%
  detailed_entries(comment, Year, Award, Institution)



```

